# Generated by Django 3.1.5 on 2021-04-07 04:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('codigo_qr', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('horas', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(blank=True, upload_to='qr_codes')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('no_control', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999)], verbose_name='Numero de control')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre(s)')),
                ('apellidos', models.CharField(max_length=250)),
                ('carrera', models.CharField(choices=[('Ingenieria en Sistemas Computacionales', 'Ingenieria en Sistemas Computacionales'), ('Ingenieria Industrial', 'Ingenieria Industrial'), ('Ingenieria en Gestion Empresarial', 'Ingenieria en Gestion Empresarial'), ('Licenciatura en Administracion', 'Licenciatura en Administracion')], max_length=250)),
                ('correo', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=250, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Conferencista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=250)),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre(s)')),
                ('apellidos', models.CharField(max_length=250)),
                ('departamento', models.CharField(choices=[('Economico y Administrativo', 'Economico y Administrativo'), ('Ciencias Basicas', 'Ciencias Basicas'), ('Metal-Mecanica', 'Metal-Mecanica'), ('Electrica y Electronica', 'Electrica y Electronica'), ('Desarrollo Academico', 'Desarrollo Academico'), ('Sistemas y Computacion', 'Sistemas y Computacion'), ('Ingenieria Industrial', 'Ingenieria Industrial'), ('Division de Estudios Profesionales', 'Division de Estudios Profesionales'), ('Posgrado e Investigacion', 'Posgrado e Investigacion'), ('Coordinacion de Educacion a Distancia', 'Coordinacion de Educacion a Distancia'), ('Planeacion, Programacion y Presupuestacion', 'Planeacion, Programacion y Presupuestacion'), ('Comunicacion y Difucion', 'Comunicacion y Difucion'), ('Servicios Escolares', 'Servicios Escolares'), ('Gestion Tecnologia y Vinculacion', 'Gestion Tecnologia y Vinculacion'), ('Actividades Extraescolares (Formacion Integral)', 'Actividades Extraescolares (Formacion Integral)'), ('Centro de Informacion (Biblioteca)', 'Centro de Informacion (Biblioteca)')], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnetApp.actividad')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnetApp.alumno')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='impartidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnetApp.conferencista'),
        ),
    ]
