# Generated by Django 3.1.6 on 2021-02-22 06:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('codigo_qr', models.CharField(max_length=500, primary_key=True, serialize=False, verbose_name='Codigo QR')),
                ('nombre', models.CharField(max_length=250)),
                ('horas', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('no_control', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999)], verbose_name='Numero de control')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre(s)')),
                ('apellidos', models.CharField(max_length=250)),
                ('carrera', models.CharField(choices=[('ing-sistemas-computacionales', 'Ingenieria en Sistemas Computacionales'), ('ing-industrial', 'Ingenieria Industrial'), ('ing-gestion-empresarial', 'Ingenieria en Gestion Empresarial'), ('lic-administracion', 'Licenciatura en Administracion')], max_length=250)),
                ('correo', models.EmailField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Conferencista',
            fields=[
                ('correo', models.EmailField(max_length=250, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre(s)')),
                ('apellidos', models.CharField(max_length=250)),
                ('departamento', models.CharField(choices=[('economico-administrativo', 'Economico y Administrativo'), ('ciencias-basicas', 'Ciencias Basicas'), ('metal-mecanica', 'Metal-Mecanica'), ('electrica-electronica', 'Electrica y Electronica'), ('desarrollo-academico', 'Desarrollo Academico'), ('sistemas-computacion', 'Sistemas y Computacion'), ('ingenieria-industrial', 'Ingenieria Industrial'), ('division-estudios-Profesionales', 'Division de Estudios Profesionales'), ('posgrado-investigacion', 'Posgrado e Investigacion'), ('coordinacion-educacion-distancia', 'Coordinacion de Educacion a Distancia'), ('planeacion-programacion-presupuestacion', 'Planeacion, Programacion y Presupuestacion'), ('comunicacion-difucion', 'Comunicacion y Difucion'), ('servicios-escolares', 'Servicios Escolares'), ('gestion-tecnologia-vinculacion', 'Gestion Tecnologia y Vinculacion'), ('actividades-extraescolares', 'Actividades Extraescolares (Formacion Integral)'), ('centro-informacion', 'Centro de Informacion (Biblioteca)')], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnetApp.actividad')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnetApp.alumno')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='impartidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnetApp.conferencista'),
        ),
    ]
