# Generated by Django 3.1.5 on 2021-05-24 01:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('codigo_qr', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('horas', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(blank=True, upload_to='qr_codes')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('no_control', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999)], verbose_name='Numero de control')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre(s)')),
                ('apellidos', models.CharField(max_length=250)),
                ('correo', models.EmailField(max_length=250, unique=True)),
                ('password', models.CharField(default='Tecno#2K', max_length=250, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conferencista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=250, unique=True)),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre(s)')),
                ('apellidos', models.CharField(max_length=250)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnetApp.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnetApp.actividad')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnetApp.alumno')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnetApp.carrera'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='impartidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnetApp.conferencista'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo')),
                ('first_name', models.CharField(max_length=255, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('img', models.ImageField(blank=True, null=True, upload_to='usuarios/', verbose_name='Foto de perfil')),
                ('user_active', models.BooleanField(default=True, verbose_name='Usuario activo')),
                ('user_admin', models.BooleanField(default=False, verbose_name='Usuario administrador')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
