# Generated by Django 3.1.5 on 2021-04-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnetApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='password',
            field=models.CharField(default='Tecno#2K', max_length=250, verbose_name='Contraseña'),
        ),
    ]
