# Generated by Django 3.1.5 on 2021-02-08 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnetApp', '0002_auto_20210208_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='departamento',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='no_control',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999)], verbose_name='Numero de control'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=250, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='conferencista',
            name='nombre',
            field=models.CharField(max_length=250, verbose_name='Nombre(s)'),
        ),
    ]
